name: template
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  bloc: ^8.1.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  awesome_notifications: ^0.6.21    # local notifications
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeue-Medium.otf
          weight: 500
        - asset: assets/fonts/HelveticaNeue-Roman.otf
          weight: 600
        - asset: assets/fonts/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue-Bold-Condensed.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue-Bold-Condensed-Oblique.otf
          weight: 900
